/* Generated By:JavaCC: Do not edit this line. AimConstants.java */
package modelezAim;

public interface AimConstants {

  int EOF = 0;
  int MODEL = 5;
  int EQUATION = 6;
  int EQ = 7;
  int EQTYPE = 8;
  int ENDOG = 9;
  int END = 10;
  int PROMPT = 11;
  int DATA = 12;
  int DTRM = 13;
  int NOTD = 14;
  int IMPOSED = 15;
  int STOCH = 16;
  int LAG = 17;
  int ELAG = 18;
  int LEAD = 19;
  int ENDOGENOUS = 20;
  int EXOGENOUS = 21;
  int FILEMOD = 22;
  int INNOV = 23;
  int PLUS = 24;
  int MINUS = 25;
  int MULTIPLY = 26;
  int DIVIDE = 27;
  int EXP = 28;
  int FLOAT = 29;
  int FLOATBASE = 30;
  int INTEGER = 31;
  int DIGIT = 32;
  int IDENTIFIER = 33;
  int LETTER = 34;
  int COMMA = 35;
  int EQUALS = 36;
  int OPENPAREN = 37;
  int CLOSEPAREN = 38;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"MODEL\"",
    "\"EQUATION\"",
    "\"EQ\"",
    "\"EQTYPE\"",
    "\"ENDOG\"",
    "\"END\"",
    "\">\"",
    "\"_DATA\"",
    "\"_DTRM\"",
    "\"_NOTD\"",
    "\"IMPOSED\"",
    "\"STOCH\"",
    "\"LAG\"",
    "\"ELAG\"",
    "\"LEAD\"",
    "<ENDOGENOUS>",
    "<EXOGENOUS>",
    "<FILEMOD>",
    "<INNOV>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<EXP>",
    "<FLOAT>",
    "<FLOATBASE>",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
  };

}
